create table if not exists public.guild_configs (
  guild_id text primary key,
  guild_name text,
  ticket_category_id text,
  ticket_category_name text,
  staff_role_id text,
  server_prompt text,
  server_info text,
  plan text not null default 'free',
  voice_support_enabled boolean not null default false,
  voice_category_id text,
  voice_category_name text,
  panels jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.tickets (
  channel_id text primary key,
  guild_id text not null,
  guild_name text,
  channel_name text,
  category_id text,
  opened_by text,
  voice_channel_id text,
  voice_channel_name text,
  voice_created_at timestamptz,
  status text not null default 'open',
  ai_disabled boolean not null default false,
  ai_disabled_by text,
  ai_disabled_at timestamptz,
  exam_state jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tickets_guild_id_idx on public.tickets (guild_id);
create index if not exists tickets_created_at_idx on public.tickets (created_at desc);
create index if not exists tickets_status_idx on public.tickets (status);
create index if not exists tickets_voice_channel_id_idx on public.tickets (voice_channel_id);

create table if not exists public.transcript_messages (
  id bigint generated by default as identity primary key,
  channel_id text not null,
  guild_id text,
  message_id text,
  author_id text,
  author_name text,
  author_bot boolean not null default false,
  role text,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists transcript_messages_channel_id_idx on public.transcript_messages (channel_id);
create index if not exists transcript_messages_created_at_idx on public.transcript_messages (created_at);

alter table public.guild_configs add column if not exists staff_role_id text;
alter table public.guild_configs add column if not exists server_prompt text;
alter table public.guild_configs add column if not exists server_info text;
alter table public.guild_configs add column if not exists plan text not null default 'free';
alter table public.guild_configs add column if not exists voice_support_enabled boolean not null default false;
alter table public.guild_configs add column if not exists voice_category_id text;
alter table public.guild_configs add column if not exists voice_category_name text;
alter table public.guild_configs add column if not exists panels jsonb not null default '[]'::jsonb;
alter table public.tickets add column if not exists voice_channel_id text;
alter table public.tickets add column if not exists voice_channel_name text;
alter table public.tickets add column if not exists voice_created_at timestamptz;
alter table public.tickets add column if not exists ai_disabled boolean not null default false;
alter table public.tickets add column if not exists ai_disabled_by text;
alter table public.tickets add column if not exists ai_disabled_at timestamptz;
alter table public.tickets add column if not exists exam_state jsonb;

create table if not exists public.global_blacklist (
  user_id text primary key,
  ban_code text not null unique,
  reason text not null,
  duration text not null default 'permanente',
  expires_at timestamptz,
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists global_blacklist_ban_code_idx on public.global_blacklist (ban_code);
create index if not exists global_blacklist_active_idx on public.global_blacklist (active);
create index if not exists global_blacklist_expires_at_idx on public.global_blacklist (expires_at);

create table if not exists public.global_blacklist_evidence (
  id bigint generated by default as identity primary key,
  user_id text not null,
  ban_code text not null,
  attachment_url text not null,
  proxy_url text,
  file_name text,
  content_type text,
  description text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists global_blacklist_evidence_user_id_idx on public.global_blacklist_evidence (user_id);
create index if not exists global_blacklist_evidence_ban_code_idx on public.global_blacklist_evidence (ban_code);

create table if not exists public.ticket_feedback (
  id text primary key,
  guild_id text not null,
  guild_name text,
  channel_id text not null,
  channel_name text,
  user_id text,
  username text,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  source text not null default 'dm_rating',
  public_review_posted boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists ticket_feedback_guild_id_idx on public.ticket_feedback (guild_id);
create index if not exists ticket_feedback_channel_id_idx on public.ticket_feedback (channel_id);
create index if not exists ticket_feedback_rating_idx on public.ticket_feedback (rating);
create index if not exists ticket_feedback_created_at_idx on public.ticket_feedback (created_at desc);

create table if not exists public.ai_quality_signals (
  id text primary key,
  guild_id text not null,
  guild_name text,
  channel_id text not null,
  channel_name text,
  message_id text,
  user_id text,
  username text,
  category text not null default 'general',
  severity text not null default 'medium',
  sentiment text,
  confidence integer not null default 70 check (confidence >= 0 and confidence <= 100),
  reason text,
  user_message text not null,
  previous_ai_message text,
  detected_by text not null default 'ai',
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists ai_quality_signals_guild_id_idx on public.ai_quality_signals (guild_id);
create index if not exists ai_quality_signals_channel_id_idx on public.ai_quality_signals (channel_id);
create index if not exists ai_quality_signals_user_id_idx on public.ai_quality_signals (user_id);
create index if not exists ai_quality_signals_category_idx on public.ai_quality_signals (category);
create index if not exists ai_quality_signals_severity_idx on public.ai_quality_signals (severity);
create index if not exists ai_quality_signals_resolved_idx on public.ai_quality_signals (resolved);
create index if not exists ai_quality_signals_created_at_idx on public.ai_quality_signals (created_at desc);

create table if not exists public.premium_purchases (
  id text primary key,
  discord_user_id text not null,
  buyer_username text,
  provider text not null default 'paypal',
  provider_session_id text unique,
  provider_payment_intent_id text,
  amount_total integer,
  currency text not null default 'eur',
  slots_purchased integer not null default 3 check (slots_purchased >= 1),
  slots_used integer not null default 0 check (slots_used >= 0),
  status text not null default 'paid',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists premium_purchases_discord_user_id_idx on public.premium_purchases (discord_user_id);
create index if not exists premium_purchases_provider_session_id_idx on public.premium_purchases (provider_session_id);
create index if not exists premium_purchases_status_idx on public.premium_purchases (status);
create index if not exists premium_purchases_created_at_idx on public.premium_purchases (created_at desc);
alter table public.premium_purchases add column if not exists expires_at timestamptz;
create index if not exists premium_purchases_expires_at_idx on public.premium_purchases (expires_at);

create table if not exists public.premium_slot_activations (
  id text primary key,
  purchase_id text not null references public.premium_purchases(id) on delete cascade,
  discord_user_id text not null,
  guild_id text not null,
  guild_name text,
  activated_by text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists premium_slot_activations_purchase_id_idx on public.premium_slot_activations (purchase_id);
create index if not exists premium_slot_activations_discord_user_id_idx on public.premium_slot_activations (discord_user_id);
create index if not exists premium_slot_activations_guild_id_idx on public.premium_slot_activations (guild_id);
create unique index if not exists premium_slot_activations_one_active_guild_idx
  on public.premium_slot_activations (guild_id)
  where active = true;
alter table public.premium_slot_activations add column if not exists expires_at timestamptz;
create index if not exists premium_slot_activations_expires_at_idx on public.premium_slot_activations (expires_at);

create table if not exists public.affiliate_profiles (
  discord_user_id text primary key,
  username text,
  code text not null unique,
  reward_threshold integer not null default 7 check (reward_threshold >= 1),
  reward_slots integer not null default 1 check (reward_slots >= 1),
  reward_days integer not null default 30 check (reward_days >= 1),
  total_redemptions integer not null default 0 check (total_redemptions >= 0),
  rewards_earned integer not null default 0 check (rewards_earned >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists affiliate_profiles_code_idx on public.affiliate_profiles (code);
create index if not exists affiliate_profiles_total_redemptions_idx on public.affiliate_profiles (total_redemptions desc);

create table if not exists public.affiliate_redemptions (
  id text primary key,
  code text not null,
  owner_discord_user_id text not null,
  guild_id text not null unique,
  guild_name text,
  redeemed_by_user_id text,
  redeemed_by_username text,
  reward_granted boolean not null default false,
  reward_purchase_id text,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_redemptions_owner_idx on public.affiliate_redemptions (owner_discord_user_id);
create index if not exists affiliate_redemptions_code_idx on public.affiliate_redemptions (code);
create index if not exists affiliate_redemptions_created_at_idx on public.affiliate_redemptions (created_at desc);
