create table if not exists public.guild_configs (
  guild_id text primary key,
  guild_name text,
  ticket_category_id text,
  ticket_category_name text,
  staff_role_id text,
  server_prompt text,
  server_info text,
  panels jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.tickets (
  channel_id text primary key,
  guild_id text not null,
  guild_name text,
  channel_name text,
  category_id text,
  opened_by text,
  status text not null default 'open',
  ai_disabled boolean not null default false,
  ai_disabled_by text,
  ai_disabled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tickets_guild_id_idx on public.tickets (guild_id);
create index if not exists tickets_created_at_idx on public.tickets (created_at desc);

create table if not exists public.transcript_messages (
  id bigint generated by default as identity primary key,
  channel_id text not null,
  guild_id text,
  message_id text,
  author_id text,
  author_name text,
  author_bot boolean not null default false,
  role text,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists transcript_messages_channel_id_idx on public.transcript_messages (channel_id);
create index if not exists transcript_messages_created_at_idx on public.transcript_messages (created_at);

alter table public.guild_configs add column if not exists staff_role_id text;
alter table public.guild_configs add column if not exists server_prompt text;
alter table public.tickets add column if not exists ai_disabled boolean not null default false;
alter table public.tickets add column if not exists ai_disabled_by text;
alter table public.tickets add column if not exists ai_disabled_at timestamptz;
