import 'dotenv/config';
import { z } from 'zod';

const envBoolean = z.preprocess((value) => {
  if (typeof value === 'string') {
    return ['1', 'true', 'yes', 'on'].includes(value.toLowerCase());
  }
  return value;
}, z.boolean());

const schema = z.object({
  DISCORD_TOKEN: z.string().min(1),
  DISCORD_CLIENT_ID: z.string().min(1),
  DISCORD_CLIENT_SECRET: z.string().optional(),
  DISCORD_GUILD_ID: z.string().optional(),
  DISCORD_MESSAGE_CONTENT_INTENT: envBoolean.default(false),
  DISCORD_GUILD_MEMBERS_INTENT: envBoolean.default(false),
  RUN_BOT: envBoolean.default(true),
  BOT_HA_ENABLED: envBoolean.default(false),
  BOT_INSTANCE_ID: z.string().optional().default(''),
  BOT_LEASE_TTL_MS: z.coerce.number().int().min(5000).max(120000).default(12000),
  BOT_LEASE_RENEW_MS: z.coerce.number().int().min(1500).max(60000).default(4000),
  BOT_FAILOVER_POLL_MS: z.coerce.number().int().min(1000).max(60000).default(2500),
  PORT: z.coerce.number().default(3000),
  DASHBOARD_PUBLIC_URL: z.string().url().default('http://localhost:3000'),
  SESSION_SECRET: z.string().default('dev-session-secret'),
  DOCS_TOTP_SECRET: z.string().optional().default(''),
  DOCS_TOTP_ISSUER: z.string().default('NexaDesk'),
  DOCS_TOTP_ACCOUNT: z.string().default('owner@nexadesk'),
  DOCS_SESSION_MINUTES: z.coerce.number().int().min(5).max(240).default(20),
  ADMIN_CODE_ROLE_ID: z.string().default('1499803857042280488'),
  DATA_DIR: z.string().default('./data'),
  SUPABASE_URL: z.string().url().optional().or(z.literal('')),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  AI_PROVIDER: z.enum(['groq', 'ollama', 'openai-compatible', 'disabled']).default('groq'),
  GROQ_API_KEY: z.string().optional(),
  GROQ_FALLBACK_API_KEYS: z.string().optional().default(''),
  GROQ_MODEL: z.string().default('llama-3.1-8b-instant'),
  GROQ_VISION_MODEL: z.string().default('meta-llama/llama-4-scout-17b-16e-instruct'),
  GROQ_STT_MODEL: z.string().default('whisper-large-v3-turbo'),
  GROQ_TTS_MODEL: z.string().default('canopylabs/orpheus-v1-english'),
  GROQ_TTS_VOICE: z.string().default('hannah'),
  PIPER_TTS_BIN: z.string().default('/home/pi/nexadesk/vendor/piper/piper'),
  PIPER_TTS_MODEL: z.string().default('/home/pi/nexadesk/models/piper/es_ES-davefx-medium.onnx'),
  PIPER_TTS_CONFIG: z.string().default('/home/pi/nexadesk/models/piper/es_ES-davefx-medium.onnx.json'),
  PIPER_TTS_LENGTH_SCALE: z.coerce.number().min(0.75).max(1.35).default(0.96),
  PIPER_TTS_NOISE_SCALE: z.coerce.number().min(0.1).max(1.2).default(0.62),
  PIPER_TTS_NOISE_W: z.coerce.number().min(0.1).max(1.5).default(0.75),
  OLLAMA_BASE_URL: z.string().url().default('http://192.168.1.52:11434'),
  OLLAMA_MODEL: z.string().default('llama3.2:3b'),
  OPENAI_COMPAT_BASE_URL: z.string().url().default('http://192.168.1.52:8080/v1'),
  OPENAI_COMPAT_MODEL: z.string().default('tinyllama'),
  OPENAI_COMPAT_API_KEY: z.string().default('local'),
  AKIOMAE_API_KEY: z.string().optional().default(''),
  AKIOMAE_BASE_URL: z.string().url().default('https://api.akiomae.xyz'),
  AI_MAX_HISTORY_MESSAGES: z.coerce.number().int().min(1).max(50).default(20),
  AI_VISUAL_ANALYSIS: envBoolean.default(true),
  AI_VIDEO_FRAME_COUNT: z.coerce.number().int().min(1).max(5).default(3),
  AI_VIDEO_MAX_BYTES: z.coerce.number().int().min(1_000_000).max(100_000_000).default(25_000_000),
  AI_AUTO_REPLY: envBoolean.default(true),
  ANNOUNCEMENT_MIRROR_ENABLED: envBoolean.default(true),
  ANNOUNCEMENT_SOURCE_GUILD_ID: z.string().default('1483534853524947112'),
  ANNOUNCEMENT_SOURCE_CHANNEL_ID: z.string().default('1499807075021095015'),
  ANNOUNCEMENT_MIRROR_ALLOW_MENTIONS: envBoolean.default(false),
  TOPGG_API_TOKEN: z.string().optional().default(''),
  TOPGG_API_BASE_URL: z.string().url().default('https://top.gg/api'),
  TOPGG_LOOKUP_TIMEOUT_MS: z.coerce.number().int().min(800).max(15000).default(4500),
  SECURITY_LAB_BOT_IDS: z.string().optional().default(''),
  VOICE_STT_ENABLED: envBoolean.default(true),
  VOICE_TTS_ENABLED: envBoolean.default(true),
  VOICE_TTS_PROVIDER: z.enum(['auto', 'groq', 'edge', 'piper', 'espeak']).default('auto'),
  VOICE_TTS_LOCAL_FIRST: envBoolean.default(false),
  EDGE_TTS_BIN: z.string().default('/home/pi/nexadesk/vendor/edge-tts-venv/bin/edge-tts'),
  EDGE_TTS_VOICE: z.string().default('es-ES-ElviraNeural'),
  EDGE_TTS_RATE: z.string().default('+8%'),
  EDGE_TTS_PITCH: z.string().default('+0Hz'),
  EDGE_TTS_VOLUME: z.string().default('+0%'),
  VOICE_TTS_MAX_CHARS: z.coerce.number().int().min(120).max(900).default(320),
  VOICE_MAX_RECORDING_MS: z.coerce.number().int().min(2_000).max(30_000).default(12_000),
  VOICE_MIN_RECORDING_MS: z.coerce.number().int().min(250).max(5_000).default(900),
  VOICE_SILENCE_DURATION_MS: z.coerce.number().int().min(350).max(2_000).default(650),
  FFMPEG_BIN: z.string().default('ffmpeg')
});

export const config = schema.parse(process.env);
